name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17 (must match your pom.xml)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # 3️⃣ Verify Java version (optional, for debugging)
      - name: Check Java version
        run: java -version

      # 4️⃣ Build project with Maven
      - name: Build with Maven
        run: mvn -B package --file lab/lab2/EmployeePensionPlan/pom.xml

      # 5️⃣ Deploy to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file lab/lab2/EmployeePensionPlan/pom.xml
