name: Release PAMS

on:
  release:
    types: [created]

jobs:
  release:
    name: Build & Publish PAMS Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build PAMS JAR
        run: mvn -B package --file lab/lab2/PAMS/pom.xml

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: lab/lab2/PAMS/target/*.jar
